### ISSUE TITLE
Week 14 HW Feedback

### ISSUE THREAD

**Issue by albertbahia** [stvbuller/Eat-Da-Burger#1]
@stvbuller Awesome job with the homework!  

**Things to note:**
- On https://github.com/stvbuller/Eat-Da-Burger/blob/master/burger/db/schema.sql#L9 for your **schema.sql**, it would be a good idea to use the **_TIMESTAMP_** data type for your _date1_ column heading rather than using the **_DATETIME_** data type.  
- Using **_TIMESTAMP_** is better as it represents a well defined point in time, actually accounting for time zones.   **_DATETIME_** does represent a date (as found in a calendar) and time (as observed on a wall clock). 
- I found a good answer for differentiating between **_DATETIME_** and **_TIMESTAMP_** (http://stackoverflow.com/questions/409286/should-i-use-field-datetime-or-timestamp).

**Comment by stbuller** [comment]
Changed DATETIME to TIMESTAMP in schema.db and tested the app, TIMESTAMP works
